# Generated by Django 6.0.3 on 2026-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
