# Generated by Django 4.2.29 on 2026-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
